FROM node:16-alpine

WORKDIR /home

COPY . .
RUN npm install

ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN npm run build

EXPOSE 5001
RUN npm install -g serve && rm -rf public/ src/

RUN adduser -D appuser && chown appuser .
USER appuser

CMD ["serve", "-s", "-l", "5001", "build"]