FROM ubuntu:24.04

WORKDIR /home/ubuntu

RUN apt update && apt install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_16.x | bash - &&\
    apt install -y nodejs && \
    apt-get purge -y --auto-remove curl && \
    rm -rf /var/lib/apt/lists/* && \
    node -v && npm -v 

COPY . .
RUN npm install

ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN npm run build

EXPOSE 5001
RUN npm install -g serve && rm -rf public/ src/

RUN useradd -m appuser && chown appuser .
USER appuser

CMD ["serve", "-s", "-l", "5001", "build"]