FROM ubuntu:24.04

WORKDIR /home/ubuntu

RUN apt update && apt install -y wget xsel && \
    wget https://go.dev/dl/go1.16.15.linux-amd64.tar.gz && \
    rm -rf /usr/local/go && tar -C /usr/local -xzf go1.16.15.linux-amd64.tar.gz && \
    apt-get purge -y --auto-remove curl && \
    rm -rf /var/lib/apt/lists/* go1.16.15.linux-amd64.tar.gz

ENV PATH=$PATH:/usr/local/go/bin

COPY . .
RUN go build && rm -rf **/*.go cache/  common/  controller/  go.mod  go.sum pgconnection/  router/

RUN useradd -m appuser && chown appuser .
USER appuser

ENV GIN_MODE=release
EXPOSE 8080

ENV REQUEST_ORIGIN=http://localhost:5001
CMD ["./server"]


