FROM golang:1.24-alpine

WORKDIR /home

ENV PATH=$PATH:/usr/local/go/bin

COPY . .
RUN go build && \ 
    adduser -D appuser && chown appuser . && \
    rm -rf **/*.go cache/ common/ controller/ go.mod go.sum pgconnection/ router/

USER appuser

ENV GIN_MODE=release
EXPOSE 8080

ENV REQUEST_ORIGIN=http://localhost:5001
CMD ["./server"]


