FROM ubuntu:24.04

#Set WORKDIR
WORKDIR /home/ubuntu

#Set dependencies
RUN apt update && apt install -y wget

# Install Go system wide
RUN wget https://go.dev/dl/go1.16.15.linux-amd64.tar.gz
RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.16.15.linux-amd64.tar.gz
ENV PATH=$PATH:/usr/local/go/bin
#ENV PATH="/usr/local/go/bin:${PATH}"
# PATH=$PATH:/usr/local/go/bin

# Copy and build source files 
COPY . .
RUN go build

ENV GIN_MODE=release
EXPOSE 8080

ENV REQUEST_ORIGIN=http://localhost:5001
CMD ["./server"]
#ENTRYPOINT "./server"

